Metrics/LineLength:
  Max: 125
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/PerceivedComplexity:
  Max: 9
Metrics/AbcSize:
  Max: 42
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/RegexpLiteral:
  EnforcedStyle: slashes
Style/EmptyElse:
  EnforcedStyle: empty
