Metrics/LineLength:
  Max: 130
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/PerceivedComplexity:
  Max: 9
Metrics/AbcSize:
  Max: 45
Metrics/ClassLength:
  Max: 200
Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*.rake'
    - 'config/routes.rb'
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/RegexpLiteral:
  EnforcedStyle: slashes
Style/EmptyElse:
  EnforcedStyle: empty
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/AndOr:
  EnforcedStyle: conditionals
