# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_currency: <%= ENV["STRIPE_CURRENCY"] %>
  disqus_shortname: <%= ENV["DISQUS_SHORTNAME"] %>
  fablab_without_plans: <%= ENV["FABLAB_WITHOUT_PLANS"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV["D3_DATE_FORMAT"].dump %>  # .dump is needed as the value may start by a '%', see https://github.com/tenderlove/psych/issues/75
  rails_locale: <%= ENV["RAILS_LOCALE"] %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  messageformat_locale: <%= ENV["MESSAGEFORMAT_LOCALE"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  elasticsearch_language_analyzer: <%= ENV["ELASTICSEARCH_LANGUAGE_ANALYZER"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_currency: <%= ENV["STRIPE_CURRENCY"] %>
  disqus_shortname: <%= ENV["DISQUS_SHORTNAME"] %>
  fablab_without_plans: <%= ENV["FABLAB_WITHOUT_PLANS"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV["D3_DATE_FORMAT"].dump %>
  rails_locale: <%= ENV["RAILS_LOCALE"] %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  messageformat_locale: <%= ENV["MESSAGEFORMAT_LOCALE"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  elasticsearch_language_analyzer: <%= ENV["ELASTICSEARCH_LANGUAGE_ANALYZER"] %>


staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_currency: <%= ENV["STRIPE_CURRENCY"] %>
  disqus_shortname: <%= ENV["DISQUS_SHORTNAME"] %>
  fablab_without_plans: <%= ENV["FABLAB_WITHOUT_PLANS"] %>
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  delivery_method: <%= ENV['DELIVERY_METHOD'] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV["D3_DATE_FORMAT"].dump %>
  rails_locale: <%= ENV["RAILS_LOCALE"] %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  messageformat_locale: <%= ENV["MESSAGEFORMAT_LOCALE"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  elasticsearch_language_analyzer: <%= ENV["ELASTICSEARCH_LANGUAGE_ANALYZER"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_currency: <%= ENV["STRIPE_CURRENCY"] %>
  disqus_shortname: <%= ENV["DISQUS_SHORTNAME"] %>
  fablab_without_plans: <%= ENV["FABLAB_WITHOUT_PLANS"] %>
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  delivery_method: <%= ENV['DELIVERY_METHOD'] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV["D3_DATE_FORMAT"].dump %>
  rails_locale: <%= ENV["RAILS_LOCALE"] %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  messageformat_locale: <%= ENV["MESSAGEFORMAT_LOCALE"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  elasticsearch_language_analyzer: <%= ENV["ELASTICSEARCH_LANGUAGE_ANALYZER"] %>
