# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 002f8bf3338bc1a4e7b8086186c7d9b34524ccfd6076a792d41057bd7448092c837a32373ac8953403fa2e302350ac10520508094c5d12b994e554708d780503
  disqus_shortname: fablab-sleede

test:
  secret_key_base: fd566823b0f46e4d02b0a6ccd4f52dcbbe426c80cef5f85d8b2e942fddad718753fc025556cac694d15cff0010fb582c92df3283e2edb9e6d9ccf63db0ace744
  disqus_shortname: fabmanager-test

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  disqus_shortname: <%= ENV["DISQUS_SHORTNAME"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  disqus_shortname: <%= ENV["DISQUS_SHORTNAME"] %>
